import './miner'
import './smelter'
import './carpenter'
import './electronic'
import './hunter'
import './industry'
import './upgrades'
import './masonry'
import './mechanic'
import './oil'
import './tailor'

export { getResult } from './utils'
